version: '3.3'
services:
  db:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: richik
  backend:
    image: shivaspk/ecommerce_backend
    ports: 
      - "8080:8080"
    depends_on:
      - db
  frontend:
    image: shivaspk/ecommerce_frontend
    ports: 
      - "80:80"
    depends_on: 
      - backend
